apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-docker
  labels:
    app: php-docker
  namespace: deployment-php-docker
  annotations:
    monitoring: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-docker
  template:
    metadata:
      labels:
        app: php-docker
    spec:
      containers:
      - image: php-docker_php-apache-environment
        name: php-docker
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
