apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-docker
  name: php-docker
  namespace: deployment-php-docker
spec:
  ports:
  - nodePort: 30500
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-docker
  type: NodePort
